name: angular CI

on:
  pull_request:
    branches: [master]

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache@v2
      - uses: actions/cache@v2
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          node-version: 12
      - run: npm ci
      - run: npm test
      - run: npm run build
