name: angular CI

on:
  pull_request:
    branches: [master]

jobs:
  test_pull_request:
    runs-on: macos-latest
    steps:
<<<<<<< HEAD
      - uses: actions/cache@v1
=======
      - uses: actions/checkout@v2
>>>>>>> 53a0a872b75e83bf3450b81dfae58ed1c23bd1cd
      - uses: actions/setup-node@v1.1.0
        with:
          node-version: 12
      - run: npm ci
      - run: npm test
      - run: npm run build
